name: rights_hub
description: A Flutter project focused on promoting and reporting human rights issues.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  cloudinary_public: ^0.10.0
  video_player: ^2.5.1
  audioplayers: ^6.4.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sharp_logo.png
